# Generated by Django 5.0.2 on 2024-02-10 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0003_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='comments',
            index=models.Index(fields=['created'], name='blogapp_com_created_91397e_idx'),
        ),
    ]
