# Generated by Django 5.0.2 on 2024-02-10 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0004_comments_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='name',
            new_name='username',
        ),
    ]
